language: java
jdk:
- oraclejdk8
os:
- linux
sudo: true
env:
  global:
  - TERRAFORM_CMD="$TRAVIS_BUILD_DIR/terraform"
  - QUORUM_CLOUD_TEMPLATES_DIR=quorum-cloud/aws/templates
  - QUORUM_SOCKSPROXY_HOST=localhost
  - QUORUM_SOCKSPROXY_PORT=5000
  # Terraform Variables
  - TF_VAR_region=us-east-1
  - TF_VAR_is_igw_subnets=false
  - TF_VAR_subnet_ids="[\"subnet-4c30c605\",\"subnet-4c30c605\",\"subnet-09263334\",\"subnet-5236300a\"]"
  - TF_VAR_bastion_public_subnet_id="subnet-3a8d8707"
  - TF_VAR_access_bastion_cidr_blocks="[$(dig +short nat.travisci.net | sed -e 's/$/\/32\"/g' | sed -e 's/^/\"/g' | paste -s -d, -)]"
  # AWS Configuration
  - secure: "Ky3rDj1j0dFyLkTZmZCzPeu0hYlgM0egbVIr+ktXTHj2ludztP1Os0AkyORsDJSlpcLTfSpVuUpOM+s40oGgPRmHJKRtwzTjYIVnpfnqrWUjnr0p/lVn6bV2nShbZQK5Kn21ProYT9OEoboOloiG1yOx9oK25UR+tXVujIntzrbukig3pbb/g0dGMDQQD0nK9noSQR2vaK0kEpO577P8UBu3c3gvznvebS2O9yMQxbTiFMmtqAgkt+0e03sijLFgzFJKCfaPgIqOYiVNmY3VqDQZB3tkkrL4Zg+GY2tbgkYczlhQCligd5/WMtuKWWALrI26U+XDKxLrfxLowHACeLU3TY6Kfb/y33p+VRQfCavm5t6vVgJX2Bs0MhGq1hWXYjOUMSj1QvBh5MAmG+pS/ofKzEfuXZGFo7jF/92lJfOliGYdoptjpRJMr2PVjYhFMYDmabnbJuffkMMVA138NgPr3QAFkPjIDvShGvlYONv0q7st3pM3S5szlyflB8kNNkOar7bCDL1jXF/Dbm+uWSwfOmCHHzNuAwvqCmqLtYcAwcsKJfLBJxo2rgRC7/AFjiSZBEEzDe7tGAUzcUJn7Gbg6RLo/13J6DppGqCO/cxnFKhZiUOCZgF/WwUjG2VQQTh1/MJJ3iT8Cp111qKDiabBc2vpfi0H2wZpymN4fVk="
  - secure: "35Vf9BW8sfzw71+98/y/174+edCjSPegGX9Ih9615r4TahbTwZYLomt7F2plmA5rWVkk3Rj1pMQU440k3TxlKw9mRX8znQZxBBdr4M2n/xHL3xqEzFfPQYffjYiEF6+tVifJGElq8vF1KmNKuImxqLX66oI5iM0TzSzSFX+MAjEHvXQvn/nqEYmI6KmWuEcgZzKdyu5oqPhsEPqx7EdD+VFEjaYS8tp64CPRr8IKuK7vksOTyJa5TpyP4i7RRhN5+TuDJXuFlPkOMB1OBS2Co+oSQi1nhEjy0kRlzG9WlUyAhl9JRbe3L9cAe/O2QJEFCv744M13AHng7wcQYZPc2Qfxrmev3qTUM5mLcETDTYd28TNu2uJPeaqb9NKfoMoD4e6AsPnXy96nvx4KCKD9RT4fBRE4oWPvAQ+3NiGh8TM3ditFe6nBOUpBs9Tokt0J7sP8inZZM3oq5wqHrChLl0ivRE+yA1LutEkv9XLHz+Uz4lp8dacNeBIGXXvYcZDTJedlpO2rFEksJSNcLWLWITB5Sa2LOY7JUC1nd4G74SF9YxtYAZx6QYXmMi40r88/zrAO7ZYW0XPdcIoVxN/GiZxc3m5YrgOU0IwuPSGn6HveXUZqxL1eFepwIaezLbc+khqUOVMnOWTBpM4esXb2Xe5LTn9niwL8InAV8GRpz/Q="
  # Github Page configuration to publish test report
  - secure: "JGDd6xYOvHS6I5x6pHFkt4+hq9PVKtfx6sKr4xoRb2t9dXPMp8rWF01c7dUvblJD8sbxK1cqa6F5MKYyu84OICX34YU8vg16sRl/1Ug4ixHLK67FmIuqYoWpvHEf+Aw3azND3/i8WqcnmSNNA2KAlpuvjm5/gy63piHG1ROtXpIR7Wd1FK/1vto18lgqXJWJga6ZpVP9S3hRxxMgEoYL2ZVDJE/HLRgk55hEPg4uQnPIZzyPaAiVDU4ZObfZUjk2mBPx3vUxQmTv7UAXVCfYwXfrVo1pqR656QiXQb6AQuwzRoby36a4ivfkbFmgLOCqJ4MJDI1MLjKp8Uzg4qXBbTPFIXyuMfJKZDWQJv147c+oo/frbPj8qSIp2xpnCcZKwF5BzvSOK1NkoW9+tMD7VUdp6N3baEdGrA8HjNMoLQniy1pX6roHTUFWTInmfiKudknZ8Q94+E0a+u70Vv1Q+fYy7vCJL51qdW8UWuF93EzZ5vo9h7SeSf/4CD/rNIGYTTDv1TOVziLsXQBfYMvcgsADfPLD0ncD6ZSRK1BJCvBfvRCQGZPAxumbcGvUhQYmZELCb8UATMi0fh94I+Lk+MZwlaRf3ywqyS2x2YG2K8ud52AfHfIjRD8qK/KApGal3tIUczDbWxvktx4o6hNyVIxVsoPJkkFg2eysGrVBWRM="
  - REPO_NAME=QuorumEngineering.github.io
  - REPO_OWNER=QuorumEngineering
  - GITHUB_USERNAME=trung
addons:
  apt:
    update: true
    sources:
    - sourceline: ppa:ethereum/ethereum
    - sourceline: "deb https://dl.bintray.com/gauge/gauge-deb stable main"
      key_url: "http://pool.sks-keyservers.net/pks/lookup?search=0x023EDB0B&op=get&options=mr"
    packages:
    - openssh-client
    - dnsutils
    - maven
    - gauge
    - solc
    - jq
cache:
  directories:
  - $HOME/.m2
before_install:
- wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip -O terraform.zip -q
- unzip terraform.zip
- $TERRAFORM_CMD version
- git clone https://github.com/QuorumEngineering/quorum-cloud.git
install:
- gauge telemetry off
- gauge install
matrix:
  include:
  - name: raft
    env:
    - TF_VAR_consensus_mechanism=raft
    - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}
  - name: istanbul
    env:
    - TF_VAR_consensus_mechanism=istanbul
    - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}
before_script:
- ./start_quorum.sh
- set +e
script:
- ./run_tests.sh
- set +e
after_script:
- ./stop_quorum.sh
- set +e
- ./upload_test_report.sh
notifications:
  slack:
    rooms:
    - secure: "g3MDTuaYTOwc8nIvn070qMrsGOjUfXSpGoMMCxz1VxqnomieFu+U9AthT3vJwm2By/xL5eQ61vp3Lf1HZa/20hkWq+RCzQP0p33B8ny6OJK3O+xv5qNFt2KgVCI53ff4gQIWJ/SAjdvqlebiVbgHuTqjeVWt6zCQ+RMqQBgkuY3oG49Thb11LI4u8kPou4AhuBxkq7H1FrzsLzI6LH/ZsrZLbxPDkqE8KLDaUL26J7+Yk9UBaXPFg5TLV/RltKK/rJ0mUPQQYGO3IqYe7MXZY+vPOWMRMjK2Is3wiVtypJVTnqMqcTfhd6pGvW6G6BL1V45ODiNAShQmWH7umxs6ZrPUaWOpYImVvXrFo6FOaamwjoSlBFEzG+vuTfYQLaRUCA+w2mG9scIdOupGyQx4sUSq6a784fK+as5T5mNGLYa5sI6OJc28dshDt2OHRT+7FwOOsTHUmpQa4zmzKt/7m420A3bkFY/F7vY3qyCJF/jrPV+DFghtJhwJRQelOWDgzeTxerhRPB176S5YfXOje2rLsK03GtVboq5Iq9JwjbAKaq5U+P19WxIf9EfFHqp/mHf3HYAC9ULrfgsWk2FAFBDtCrwhCJxtbUqo/Zf+/KKUqvVeKcfpCTfZNEIwO7v2tvgTLGdhh4EYibPz6BeQ535tP2/2961lqeqrslYnZdo="
    on_success: change
    on_failure: always
    on_pull_requests: false
    template:
    - "Build <%{build_url}|#%{build_number}> of %{repository_slug}@%{branch}"
    - "%{result} in %{duration}"
    - "<https://quorumengineering.github.io/%{repository_name}/docs/html/|Specifications> - <https://quorumengineering.github.io/%{repository_name}/raft/|Test Report (Raft)> - <https://quorumengineering.github.io/%{repository_name}/istanbul/|Test Report (Istanbul)>"
