language: java
jdk:
- oraclejdk8
os:
- linux
sudo: true
env:
  global:
  - TERRAFORM_CMD="$TRAVIS_BUILD_DIR/terraform"
  - QUORUM_CLOUD_TEMPLATES_DIR=quorum-cloud/aws/templates
  - QUORUM_SOCKSPROXY_HOST=localhost
  - QUORUM_SOCKSPROXY_PORT=5000
  # Terraform Variables
  - TF_VAR_region=us-east-1
  - TF_VAR_is_igw_subnets=false
  - TF_VAR_subnet_ids="[\"subnet-4c30c605\",\"subnet-4c30c605\",\"subnet-09263334\",\"subnet-5236300a\"]"
  - TF_VAR_bastion_public_subnet_id="subnet-3a8d8707"
  - TF_VAR_access_bastion_cidr_blocks="[$(dig +short nat.travisci.net | sed -e 's/$/\/32\"/g' | sed -e 's/^/\"/g' | paste -s -d, -)]"
  # AWS Configuration
  - secure: "cnHFg4wHhEWJAnEdKckMGrUV7EvqTRHhHaDG3kLppaWdqlTKu2yfciaoeYG+WnWqPf4p3LKEw/7cfroGfOqvFr31BTySBMTb98Rjp0qFdW2ZlAa7EVn1Ou3vmpDdMXEbpHNHIC+YxUOpNaati4FeKzNvICThnTchnRFXAM1+oQONGi9AAsrv+xCdnyWBeZZxqA7bIzb3QQosh+0kig+ciCWV/MQu+Waiuog8P1STfV56pC4O+H2qhKuLHI0f3LNueZSdxnFZdbtFptAoCpEWGU6JWPT7weMVShwpzLyg9ZvEjVN9ixkPvHSq27f3i5FyH4965QMuRnfNLA3auR1zDAuaSxwUd51nkSSPWIfV2YdYWZ73y+v6nsaaIywMjX9kxRCTMP6Oskkl5K+QNYafaz/D1x0so14erP3QwJWcSjl+UuN9teAEWJrRzTzX+u8yq/3T8zB9khs3009pqyazTHB0MVjNzJ1dO6dYINMq6UApBcEKLZm8yQxJisQsElJaCROC2Z/EaSuaHEXa6arKKwd9oIeO9B7/zOcS76Llb1GXIjYoGvuug54g477sWhgfKaqy2ykKdSjUtvx6vYi4s/s9WisIxdnqpN+1RFABXbSlIVhxD524UNAQJlav16h8Z6isv16llik3Ya7XbQbJR2K7qzUTuvP9F6Dx+wfFx84="
  - secure: "f1mXiAlFxnmXhLn+cNbjwwaAzfZBlMkEzYo1HMjcp+H9Co9PcPsyV8TXQRXLAbcV8j/xSKv1X0Fqex62jchr3g+MEvRj9Ls55cGyNdyESugYJBxUsVucILZC85Mkl8FB1qLcgfF86WdMWeE3oMseT3h7jYzr3jlZJtpCjdQtZWrUhWvfT9Sd/97kpRvAv81xXd7Wgp6LX+xHrdxA3iMj/3487kQIlO6uA4KzIdqIdIQ/Nv1czV4hMcBV0OTp+PiyLSK3nFHnPEpMM4cxMQta6zk+XbB0yFB3fqXv7n1E6kIioo4/egylS21PVouT165L/0tTehfxAY4o1UPbSvA0FnOQnHWT815vVu2T0MBcYOyQxCiYzQVP702x9QgMfvWH7P4SVIt3LY18h92H2YHK1W79fmkFPj3LBe8vKDFReLewDK46Blm2Ewo3G7gS7HTTTZmp35+c3Y9zzIP4Rs+/6CAVCPL/oXRvu5o+p/bE6KmPkZAGLn7MinHKv8WsS2ZB26Db142bmz+Bqi2Zp40uMHMJx75xkM+8Jx4+kuJDdbMU+YNFwUKinPR1m3MOOthhNDPd0Xf3D4NY1T0F8inG4PSr0xCj9WpPwPCz7swwN5v3phoi3Vjlgs/vClksXPQU4OnKqzyHNAEBpV7x/uylbP5n75mN8/m2TTsiQpWeIzk="
  # Github Page configuration to publish test report
  - secure: "xxDMUYszTo6x5y4jaZevN2IN6hDAzn3VaAUkUAFDkGqSY6FBgLPVRll9kompw9UTkfAuAeQA3T2p8ekYU3Y6nEh2Qaq0wpAVGncGnIfLP7XPuiW5rpATWoXN6lq0visVC6SEkXvyNQ5sZxLlrU2PWd7w6ArefDls5TK/FSlUMGHf85LjaXHAo7bcAqjjUPs3tx/Txkc8q4m0M8iu27Mp3p5Z11Svhsh62XGiZbpTBj0GZtF+/nAUo982w2Zy8NZ85CVCeLbWtQUTdzmYv8e//SY/XQrFz68BYWODDF3W4QcC2jPdHwodfCL0TMOQUQYGp9oXu6dRVU4nIESbXf89uSAPfn4YS3GTQHfb42flJXlZpY31sZtI5xCLO366iqvFw2fkBKvguHUEkk0uIMkyZxRu6MNJStk4BtALvNVVfA0lyIyFqrxWc2/82D5EPJcnhTSxpLr1o4opMJhfDjcIXK/igLpW/h5CxBaRs/V6zY0dmplvfauP37l3u8mWLkRfFI4CZw/jML6mkH6It6KuDzCgS8f3b3uboBscfXXg8qMn6XxCKbkqOsaseCWygMaMQq/yw2NePVkuJ7h8MZu/Pf7unL3x8tVPo8or3R5+C/QYqqTvNbHhwcIhi1y8GJIfjc1/91P1S8Rd1IlT4EOCw4Ql1VSVR1J0J/PUE6sq59o="
  - REPO_NAME=trung.github.com
  - REPO_OWNER=trung
  - GITHUB_USERNAME=trung
addons:
  apt:
    update: true
    sources:
    - sourceline: ppa:ethereum/ethereum
    - sourceline: "deb https://dl.bintray.com/gauge/gauge-deb stable main"
      key_url: "http://ha.pool.sks-keyservers.net/pks/lookup?search=0x023EDB0B&op=get&options=mr"
    packages:
    - openssh-client
    - dnsutils
    - maven
    - gauge
    - solc
    - jq
cache:
  directories:
  - $HOME/.m2
before_install:
- wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip -O terraform.zip -q
- unzip terraform.zip
- $TERRAFORM_CMD version
- git clone https://github.com/trung/quorum-cloud.git
install:
- gauge telemetry off
- gauge install
matrix:
  include:
  - name: raft
    env:
    - TF_VAR_consensus_mechanism=raft
    - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}
  - name: istanbul
    env:
    - TF_VAR_consensus_mechanism=istanbul
    - TF_VAR_network_name=ci-${TF_VAR_consensus_mechanism}-${TRAVIS_COMMIT::6}
before_script:
- ./start_quorum.sh
- set +e
script:
- ./run_tests.sh
- set +e
after_script:
- ./stop_quorum.sh
- set +e
- ./upload_test_report.sh
notifications:
  slack:
    rooms:
    - secure: "6h88IhBfc3zURO+j51g7oggjzu7ENp9LY32/UJLdx8gkP1Vczhm4NoRBIsBij2hKuNzae3E+GFpI2223F63nEm/k9qtvHNjHZKFlqh70HOpFCs/PHV21kjYkWnlxgIcc3LXaXmscNJQlyPTiWvsf2HzJCkY7FmQs5WmmzRa4GeXvlxLuD07NBd8P4k9l89gtiN7XXy065eXpG/iQ1dSZ/I7ifF0WmxqYsAkAMawh3CoZeNq6Q0ej2MhDblNTTPkA3EUeXi5ihj+kpQ5Lh1vup0zBfKHaQAes5K6dL3gHoO+dgP9cUzs4wCdOrjSSO8uXrOlNQLIHw+HpMMcK5b8CgWiO3ijTMnWmWjzPex2SOqVkyM+IyU1YxpeG5Sc4SA/kruTMIMofA6cRVA9+9ILi3rkmLHJHavhRdkVoyCy42Xj1kIYLr1bMqx9Y4tLtnXqILwuTqIs90dViBJ8ntibIvSe6uhyUN98LrUOJwR5fx0HyvCYr0VVuFiJRmQ+90JrysHi7DDasStIGbzi9uusTB3oOVgJ4YJPAyUdEOie7TmxRRvCiEx0udnhnozZaKj4OKXS2qH0TfIJBMBrNWmJpxTcNxSbHV5rv53gvvhqCEnjiyBlRiSj/p7HM5KK2R6odNsfAUykwNK6PTTgqREkAeqhIcq1PNzunpnfFXWbnGNk="
    on_success: change
    on_failure: always
    on_pull_requests: false
    template:
    - "Build <%{build_url}|#%{build_number}> of %{repository_slug}@%{branch} %{result} in %{duration}"
    - "<https://quorumengineering.github.io/%{repository_name}/docs/html/|Specifications> - <https://quorumengineering.github.io/%{repository_name}/raft/|Test Report (Raft)> - <https://quorumengineering.github.io/%{repository_name}/istanbul/|Test Report (Istanbul)>"
