language: java
jdk:
  - oraclejdk8
os:
  - linux
sudo: true
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:ethereum/ethereum'
      - sourceline: 'deb https://dl.bintray.com/gauge/gauge-deb stable main'
        key_url: 'http://pool.sks-keyservers.net/pks/lookup?search=0x023EDB0B&exact=on&options=mr&op=get'
    packages:
      - maven
      - gauge
      - solc
      - jq
install:
  - gauge telemetry off
script:
  - gauge install
  - mvn clean test -q