# This is just a sample of how application-local.yml should be:
quorum:
  # This is required only if socks proxy is used
  # Typically when Quorum Network is provisioned with quorum-cloud
  socks-proxy:
    host: localhost
    port: 5000
  # Metadata about nodes in the network
  nodes:
    Node1:
      privacy-address: xjF8q8yEn9NvpT6QMQ5/KDxsrNJUxXPsJz+eiowLVFk=
      url: http://172.31.106.65:22000
    Node2:
      privacy-address: PWq8vjGvlZxQjM0uUkDGSkuaNfrBC3ktIh9iRrKp+Qw=
      url: http://172.31.98.75:22000
    Node3:
      privacy-address: wCHD/0T3u9vFvsKvbEsHeLl+NMrvoZMd08QOSon6vxU=
      url: http://172.31.107.18:22000
    Node4:
      privacy-address: ZRZocxoQEJfGCsNjZUxWxDOQfz1nOkdlkqFjBy9MbyE=
      url: http://172.31.85.125:22000
    Node5:
      privacy-address: Bw/MSUKwiyHaSixsBBikhR1GohP0R4BmZDL6r3XJfR4=
      url: http://172.31.89.24:22000
    Node6:
      privacy-address: ONr2l4AxptXy0ef1rwECvQkoJsz3J63pb0C9kTWsBnI=
      url: http://172.31.93.207:22000
    Node7:
      privacy-address: 3FWFk/qBfy9KVf2R0oYaki3tnEIWtkEY/F7zNdsCIF4=
      url: http://172.31.125.149:22000